### ISSUE TITLE
Silently fails to push on Ruby 1.9.3dev

### ISSUE THREAD

**Issue by mattwynne** [cucumber-ltd/relish-gem#17]
As reported by Martin Solli to support email.

```
~  ruby -v
ruby 1.9.3dev (2011-09-23 revision 33323) [x86_64-darwin11.0.1]
```

**Comment by msolli** [comment]
When I run `relish push org/project`, it sits there until I hit ctrl-c. Then I get this backtrace:

```
/Users/martin/.rbenv/versions/1.9.3-rc1/lib/ruby/1.9.1/net/protocol.rb:143:in `select': Interrupt
    from /Users/martin/.rbenv/versions/1.9.3-rc1/lib/ruby/1.9.1/net/protocol.rb:143:in `rescue in rbuf_fill'
    from /Users/martin/.rbenv/versions/1.9.3-rc1/lib/ruby/1.9.1/net/protocol.rb:140:in `rbuf_fill'
    from /Users/martin/.rbenv/versions/1.9.3-rc1/lib/ruby/1.9.1/net/protocol.rb:122:in `readuntil'
    from /Users/martin/.rbenv/versions/1.9.3-rc1/lib/ruby/1.9.1/net/protocol.rb:132:in `readline'
    from /Users/martin/.rbenv/versions/1.9.3-rc1/lib/ruby/1.9.1/net/http.rb:2562:in `read_status_line'
    from /Users/martin/.rbenv/versions/1.9.3-rc1/lib/ruby/1.9.1/net/http.rb:2551:in `read_new'
    from /Users/martin/.rbenv/versions/1.9.3-rc1/lib/ruby/1.9.1/net/http.rb:1319:in `block in transport_request'
    from /Users/martin/.rbenv/versions/1.9.3-rc1/lib/ruby/1.9.1/net/http.rb:1316:in `catch'
    from /Users/martin/.rbenv/versions/1.9.3-rc1/lib/ruby/1.9.1/net/http.rb:1316:in `transport_request'
    from /Users/martin/.rbenv/versions/1.9.3-rc1/lib/ruby/1.9.1/net/http.rb:1293:in `request'
    from /Users/martin/.rbenv/versions/1.9.3-rc1/lib/ruby/gems/1.9.1/gems/rest-client-1.6.7/lib/restclient/net_http_ext.rb:51:in `request'
    from /Users/martin/.rbenv/versions/1.9.3-rc1/lib/ruby/gems/1.9.1/gems/rest-client-1.6.7/lib/restclient/request.rb:176:in `block in transmit'
    from /Users/martin/.rbenv/versions/1.9.3-rc1/lib/ruby/1.9.1/net/http.rb:745:in `start'
    from /Users/martin/.rbenv/versions/1.9.3-rc1/lib/ruby/gems/1.9.1/gems/rest-client-1.6.7/lib/restclient/request.rb:172:in `transmit'
    from /Users/martin/.rbenv/versions/1.9.3-rc1/lib/ruby/gems/1.9.1/gems/rest-client-1.6.7/lib/restclient/request.rb:64:in `execute'
    from /Users/martin/.rbenv/versions/1.9.3-rc1/lib/ruby/gems/1.9.1/gems/rest-client-1.6.7/lib/restclient/request.rb:33:in `execute'
    from /Users/martin/.rbenv/versions/1.9.3-rc1/lib/ruby/gems/1.9.1/gems/rest-client-1.6.7/lib/restclient/resource.rb:67:in `post'
    from /Users/martin/.rbenv/versions/1.9.3-rc1/lib/ruby/gems/1.9.1/gems/relish-0.5.3/lib/relish/commands/push.rb:31:in `post'
    from /Users/martin/.rbenv/versions/1.9.3-rc1/lib/ruby/gems/1.9.1/gems/relish-0.5.3/lib/relish/commands/push.rb:18:in `block in <class:Push>'
    from /Users/martin/.rbenv/versions/1.9.3-rc1/lib/ruby/gems/1.9.1/gems/relish-0.5.3/lib/relish/commands/dsl/command.rb:11:in `instance_exec'
    from /Users/martin/.rbenv/versions/1.9.3-rc1/lib/ruby/gems/1.9.1/gems/relish-0.5.3/lib/relish/commands/dsl/command.rb:11:in `block (2 levels) in define'
    from /Users/martin/.rbenv/versions/1.9.3-rc1/lib/ruby/gems/1.9.1/gems/relish-0.5.3/lib/relish/command.rb:23:in `run'
    from /Users/martin/.rbenv/versions/1.9.3-rc1/lib/ruby/gems/1.9.1/gems/relish-0.5.3/bin/relish:11:in `<top (required)>'
    from /Users/martin/.rbenv/versions/1.9.3-rc1/bin/relish:19:in `load'
    from /Users/martin/.rbenv/versions/1.9.3-rc1/bin/relish:19:in `<main>'
```
