### ISSUE TITLE
Fails to read password on Ruby 2.0 on Windows 8

### ISSUE THREAD

**Issue by mattwynne** [cucumber-ltd/relish-gem#23]
As reported by @ptrelford.

Here's a stack trace:

```
C:\Users\Phil>relish projects:add ptrelford/cellz
Please enter your Relish credentials.
Email: ptrelford@hotmail.com
Password: DL is deprecated, please use Fiddle
C:/Ruby200-x64/lib/ruby/2.0.0/Win32API.rb:14:in `initialize': No such file or di
rectory (LoadError)
        from C:/Ruby200-x64/lib/ruby/2.0.0/Win32API.rb:14:in `dlopen'
        from C:/Ruby200-x64/lib/ruby/2.0.0/Win32API.rb:14:in `initialize'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/relish-0.6/lib/relish/ui.rb:26:in `new'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/relish-0.6/lib/relish/ui.rb:26:in `ask_for_password_on_windows'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/relish-0.6/lib/relish/ui.rb:10:in `get_credentials'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/relish-0.6/lib/relish/commands/base.rb:57:in `get_api_token'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/relish-0.6/lib/relish/commands/base.rb:51:in `get_and_store_api_token'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/relish-0.6/lib/relish/commands/base.rb:16:in `block in <class:Base>'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/relish-0.6/lib/relish/commands/dsl/option.rb:16:in `instance_exec'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/relish-0.6/lib/relish/commands/dsl/option.rb:16:in `block (2 levels) in define'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/relish-0.6/lib/relish/commands/base.rb:64:in `resource'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/relish-0.6/lib/relish/commands/projects.rb:15:in `block in <class:Projects>'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/relish-0.6/lib/relish/commands/dsl/command.rb:11:in `instance_exec'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/relish-0.6/lib/relish/commands/dsl/command.rb:11:in `block (2 levels) in define'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/relish-0.6/lib/relish/command.rb:23:in `run'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/relish-0.6/bin/relish:11:in`<top (required)>'
        from C:/Ruby200-x64/bin/relish:23:in `load'
        from C:/Ruby200-x64/bin/relish:23:in `<main>' 
```

It looks like the problem is [this code](https://github.com/relishapp/relish-gem/blob/master/lib/relish/ui.rb#L26) which uses a Win32 API call that's probably outmoded.

This looks like a better solution:
http://stackoverflow.com/questions/133719/how-can-i-read-a-password

**Comment by Stewartarmbrecht** [comment]
Any chance in getting this fixed?  I would like to use Relish but I am running on Windows 8.
Is there a work around?

**Comment by mattwynne** [comment]
There is a workaround @Stewartarmbrecht. We can manually create the token file. Email support@relishapp.com with your account details and I'll explain what you need to do.

**Comment by Stewartarmbrecht** [comment]
Thanks but I just used cloud 9 instead.

**Comment by enkessler** [comment]
@mattwynne This problem still exists and is preventing me from having my project's documentation added to Relish.

**Comment by mattwynne** [comment]
@enkessler I'm sorry to hear that. I'm afraid Relish is not a priority for us now - we're focussing on its replacement Cucumber Pro. Since I also don't have a Windows machine, it doesn't stack up for me to easily fix this.

I'd be happy to help you fix it, if you're interested to work with me on it?

**Comment by enkessler** [comment]
@mattwynne It's fine for now. I ended up digging up an older version of Ruby and using that to push out the docs.

Is there a timeline for Cucumber Pro?
